import React from 'react';
import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Button from '../components/Button';
import { signIn } from 'next-auth/react';
import { unstable_getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]';
import Image from 'next/image';
import { join } from 'tailwind-merge';

const GoogleIcon = () => {
	return (
		<svg
			className='w-5 h-5 text-white mr-2'
			focusable='false'
			aria-hidden='true'
			viewBox='0 0 24 24'
			data-testid='GoogleIcon'
		>
			<path fill='currentcolor' d='M12.545,10.239v3.821h5.445c-0.712,2.315-2.647,3.972-5.445,3.972c-3.332,0-6.033-2.701-6.033-6.032s2.701-6.032,6.033-6.032c1.498,0,2.866,0.549,3.921,1.453l2.814-2.814C17.503,2.988,15.139,2,12.545,2C7.021,2,2.543,6.477,2.543,12s4.478,10,10.002,10c8.396,0,10.249-7.85,9.426-11.748L12.545,10.239z'></path>
		</svg>
	);

	return (
		<svg
			stroke='currentColor'
			fill='currentColor'
			strokeWidth='0'
			version='1.1'
			x='0px'
			y='0px'
			viewBox='0 0 48 48'
			enableBackground='new 0 0 48 48'
			className='w-5 h-5'
			height='1em'
			width='1em'
			xmlns='http://www.w3.org/2000/svg'
		>
			<path
				fill='#FFC107'
				d='M43.611,20.083H42V20H24v8h11.303c-1.649,4.657-6.08,8-11.303,8c-6.627,0-12-5.373-12-12
	c0-6.627,5.373-12,12-12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657C34.046,6.053,29.268,4,24,4C12.955,4,4,12.955,4,24
	c0,11.045,8.955,20,20,20c11.045,0,20-8.955,20-20C44,22.659,43.862,21.35,43.611,20.083z'
			></path>
			<path
				fill='#FF3D00'
				d='M6.306,14.691l6.571,4.819C14.655,15.108,18.961,12,24,12c3.059,0,5.842,1.154,7.961,3.039l5.657-5.657
	C34.046,6.053,29.268,4,24,4C16.318,4,9.656,8.337,6.306,14.691z'
			></path>
			<path
				fill='#4CAF50'
				d='M24,44c5.166,0,9.86-1.977,13.409-5.192l-6.19-5.238C29.211,35.091,26.715,36,24,36
	c-5.202,0-9.619-3.317-11.283-7.946l-6.522,5.025C9.505,39.556,16.227,44,24,44z'
			></path>
			<path
				fill='#1976D2'
				d='M43.611,20.083H42V20H24v8h11.303c-0.792,2.237-2.231,4.166-4.087,5.571
	c0.001-0.001,0.002-0.001,0.003-0.002l6.19,5.238C36.971,39.205,44,34,44,24C44,22.659,43.862,21.35,43.611,20.083z'
			></path>
		</svg>
	);
};

const SignInPage: NextPage = () => {
	const handleSignIn = async () => {
		signIn('google');
	};

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='min-h-screen bg-slate-100'>
				<main className='container m-auto flex h-screen items-center justify-center p-8'>
					<div className={join(`flex flex-col items-center bg-white rounded shadow-md p-8 gap-4`)}>
						<h1 className='text-2xl text-slate-700 text-center'>Log In</h1>
						<Image src='/assets/sign-in.svg' alt='sign-in' width={192} height={192} />
						<p className='text-base text-slate-500 text-center'>
							Enter your credentials to access your records
						</p>
						<Button variant='primary' leftIcon={<GoogleIcon />} onClick={handleSignIn}>
							Sign in with Google
						</Button>
					</div>
				</main>
			</div>
		</>
	);
};

export default SignInPage;

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
	const session = await unstable_getServerSession(req, res, authOptions);

	if (session?.user) {
		return {
			redirect: {
				destination: '/',
				permanent: true,
			},
			props: {},
		};
	}

	return {
		props: {
			session,
		},
	};
};
